# Generated by Django 5.2.17 on 2026-10-05 12:56

import hotel.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_postgres_guards'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', hotel.models.HotelUserManager()),
            ],
        ),
    ]
