# Generated by Django 5.2.17 on 2026-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'occupied')), fields=('room',), name='one_actual_stay_per_room', violation_error_message='В номере уже проживает другой гость.'),
        ),
    ]
