# Generated by Django 5.2.17 on 2026-10-06 09:07

import django.core.validators
import hotel.fields
from decimal import Decimal
from django.db import migrations, models


def migrate_roles(apps, schema_editor):
    User = apps.get_model('hotel', 'User')
    database = schema_editor.connection.alias
    User.objects.using(database).filter(role='admin').update(role='owner')
    User.objects.using(database).filter(is_superuser=True).update(role='owner')
    User.objects.using(database).filter(role='employee').update(role='admin', is_superuser=False, is_staff=False)


def restore_roles(apps, schema_editor):
    User = apps.get_model('hotel', 'User')
    database = schema_editor.connection.alias
    User.objects.using(database).filter(role='admin').update(role='employee')
    User.objects.using(database).filter(role='owner').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_booking_one_actual_stay_per_room'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, restore_roles),
        migrations.AddField(
            model_name='booking',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сохранённый тариф за сутки, ₽'),
        ),
        migrations.AddField(
            model_name='guest',
            name='passport_issued_by',
            field=hotel.fields.EncryptedCharField(blank=True, max_length=300, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='guest',
            name='passport_issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='guest',
            name='passport_number',
            field=hotel.fields.EncryptedCharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Номер должен содержать 6 цифр.')], verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='guest',
            name='passport_series',
            field=hotel.fields.EncryptedCharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', 'Серия должна содержать 4 цифры.')], verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='room',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Тариф за сутки, ₽'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('owner', 'Владелец')], default='admin', max_length=12, verbose_name='Роль'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('daily_rate__gte', 0)), name='room_nonnegative_rate'),
        ),
    ]
